function Hd = butterworth(order, cutoffFreq1, cutoffFreq2, sampleRate, passBandGain, stopBandGain)
%BUTTERWORTH Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
% Generated on: 13-Nov-2025 18:23:25

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = sampleRate;  % Sampling Frequency

N   = order;   % Order
Fc1 = cutoffFreq1;  % First Cutoff Frequency
Fc2 = cutoffFreq2;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

% [EOF]
