function Hd = chebytwo(order, cutoffFreq1, cutoffFreq2, sampleRate, passBandGain, stopBandGain)
%CHEBYTWO Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
% Generated on: 13-Nov-2025 19:02:14

% Chebyshev Type II Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = sampleRate;  % Sampling Frequency

N      = order;    % Order
Fstop1 = cutoffFreq1;  % First Stopband Frequency
Fstop2 = cutoffFreq2;  % Second Stopband Frequency
Astop  = stopBandGain;    % Stopband Attenuation (dB)

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.bandpass('N,Fst1,Fst2,Ast', N, Fstop1, Fstop2, Astop, Fs);
Hd = design(h, 'cheby2');

% [EOF]
