function Hd = chebyone(order, cutoffFreq1, cutoffFreq2, sampleRate, passBandGain, stopBandGain)
%CHEBY1 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
% Generated on: 13-Nov-2025 18:44:52

% Chebyshev Type I Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = sampleRate;  % Sampling Frequency

N      = order;    % Order
Fpass1 = cutoffFreq1;  % First Passband Frequency
Fpass2 = cutoffFreq2;  % Second Passband Frequency
Apass  = passBandGain;     % Passband Ripple (dB)

% Construct an FDESIGN object and call its CHEBY1 method.
h  = fdesign.bandpass('N,Fp1,Fp2,Ap', N, Fpass1, Fpass2, Apass, Fs);
Hd = design(h, 'cheby1');

% [EOF]
