function Hd = elliptic(order, cutoffFreq1, cutoffFreq2, sampleRate, passBandGain, stopBandGain)
%ELLIPTIC Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
% Generated on: 13-Nov-2025 19:07:51

% Elliptic Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = sampleRate;  % Sampling Frequency

N      = order;    % Order
Fpass1 = cutoffFreq1;  % First Passband Frequency
Fpass2 = cutoffFreq2;  % Second Passband Frequency
Apass  = passBandGain;     % Passband Ripple (dB)
Astop  = stopBandGain;    % Stopband Attenuation (dB)

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.bandpass('N,Fp1,Fp2,Ast1,Ap,Ast2', N, Fpass1, Fpass2, ...
                      Astop, Apass, Astop, Fs);
Hd = design(h, 'ellip');

% [EOF]
