classdef phase2Filters_BandPass
    methods (Static)
        function Hd = butterworth(order, cutoffFreq1, cutoffFreq2, sampleRate, ~, ~)
            %BUTTERWORTH Returns a discrete-time filter object.

            % MATLAB Code
            % Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
            % Generated on: 13-Nov-2025 18:23:25

            % Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

            % All frequency values are in Hz.
            Fs = sampleRate;  % Sampling Frequency

            N   = order;   % Order
            Fc1 = cutoffFreq1;  % First Cutoff Frequency
            Fc2 = cutoffFreq2;  % Second Cutoff Frequency

            % Construct an FDESIGN object and call its BUTTER method.
            h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
            Hd = design(h, 'butter');
        end
        
        function Hd = chebyone(order, cutoffFreq1, cutoffFreq2, sampleRate, passBandGain, ~)
            %CHEBY1 Returns a discrete-time filter object.

            % MATLAB Code
            % Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
            % Generated on: 13-Nov-2025 18:44:52

            % Chebyshev Type I Bandpass filter designed using FDESIGN.BANDPASS.

            % All frequency values are in Hz.
            Fs = sampleRate;  % Sampling Frequency

            N      = order;    % Order
            Fpass1 = cutoffFreq1;  % First Passband Frequency
            Fpass2 = cutoffFreq2;  % Second Passband Frequency
            Apass  = passBandGain;     % Passband Ripple (dB)

            % Construct an FDESIGN object and call its CHEBY1 method.
            h  = fdesign.bandpass('N,Fp1,Fp2,Ap', N, Fpass1, Fpass2, Apass, Fs);
            Hd = design(h, 'cheby1');
        end

        function Hd = chebytwo(order, cutoffFreq1, cutoffFreq2, sampleRate, ~, stopBandGain)
            %CHEBYTWO Returns a discrete-time filter object.

            % MATLAB Code
            % Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
            % Generated on: 13-Nov-2025 19:02:14

            % Chebyshev Type II Bandpass filter designed using FDESIGN.BANDPASS.

            % All frequency values are in Hz.
            Fs = sampleRate;  % Sampling Frequency

            N      = order;    % Order
            Fstop1 = cutoffFreq1;  % First Stopband Frequency
            Fstop2 = cutoffFreq2;  % Second Stopband Frequency
            Astop  = stopBandGain;    % Stopband Attenuation (dB)

            % Construct an FDESIGN object and call its CHEBY2 method.
            h  = fdesign.bandpass('N,Fst1,Fst2,Ast', N, Fstop1, Fstop2, Astop, Fs);
            Hd = design(h, 'cheby2');
        end

        function Hd = elliptic(order, cutoffFreq1, cutoffFreq2, sampleRate, passBandGain, stopBandGain)
            %ELLIPTIC Returns a discrete-time filter object.

            % MATLAB Code
            % Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
            % Generated on: 13-Nov-2025 19:07:51

            % Elliptic Bandpass filter designed using FDESIGN.BANDPASS.

            % All frequency values are in Hz.
            Fs = sampleRate;  % Sampling Frequency

            N      = order;    % Order
            Fpass1 = cutoffFreq1;  % First Passband Frequency
            Fpass2 = cutoffFreq2;  % Second Passband Frequency
            Apass  = passBandGain;     % Passband Ripple (dB)
            Astop  = stopBandGain;    % Stopband Attenuation (dB)

            % Construct an FDESIGN object and call its ELLIP method.
            h  = fdesign.bandpass('N,Fp1,Fp2,Ast1,Ap,Ast2', N, Fpass1, Fpass2, ...
                                Astop, Apass, Astop, Fs);
            Hd = design(h, 'ellip');
        end
    end
end